[Service]
ExecCondition=/bin/sh -c '. /etc/os-release; ! [ -f "/storage/.cache/hwdb-${BUILD_ID:-0}" ]'
ExecStartPost=/bin/sh -c '. /etc/os-release; mkdir -p /storage/.cache && touch "/storage/.cache/hwdb-${BUILD_ID:-0}"'
